<span class="boldtext">1. How do I installed Quadro onto my wordpress blog? </span>
<div class="indent">
  <p>There are several files included in the ZIP folder. These include wordpress theme files, plugin files, and photoshop files. To installed your wordpress theme you will first need to upload the theme/plugin files via FTP to your server. </p>
  <p>First you are going to upload the theme folder. Inside the ZIP folder you downloaded you will see a folder named "theme." Within it is a folder named "Quadro." Via ftp, upload the "Quadro" folder to your Wordpress themes directory. Depending on where you installed Wordpress on your server, the wp themes folder will be located in a path similar to: /public_html/blog/wp-content/themes. </p>
  <p>Next you need to select Quadro and make it your default theme. Click on the design link, and under the themes tab locate Quadro from the selection of themes and activate it. Your blog should now be updated with your new theme. </p>
</div>
<span class="boldtext">2. How do I add the thumbnails to my homepage? </span>
<div class="indent">
  <p>Quadro utilizes a script called TimThumb to automatically resize images. Whenever you make a new post you will need to add a custom field. Scroll down below the text editor and click on the "custom fields" link. In the "Key" section, input "Thumbnail" (this is case sensitive). In the "Value" area, input the url to your thumbnail image. Your image will automatically be resized and cropped. The image must be hosted on your domain. (this is to protect against bandiwdth left) </p>
  <p>You will also need to add a second custom field for your featured articles with a Key of "Featured" and a Value of the image URL. </p>
  <p><span class="style1">Important Note: You <u>must</u> CHMOD the "cache" folder located in the Quadro directory to 777 for this script to work. You can CHMOD (change the permissions) of a file using your favorite FTP program. If you are confused try folowing <a href="http://www.siteground.com/tutorials/ftp/ftp_chmod.htm"><u>this tutorial</u></a><u>.</u> Of course instead of CHMODing the template folder (as in the tutorial) you would CHMOD the "cache" folder found within your theme's directory. </span></p>
</div>
<span class="boldtext">3. How do I add my title/logo? </span>
<div class="indent"><p>In this theme, the title/logo is an image, which means you will need an image editor to add your own text. You can do this by opening the blank logo image located at Photoshop Files/logo.jpg, or by opening the logo PSD file located at Photoshop Files/logo.psd. Replace the edited logo with the old logo by placing it in the following directory: theme/Quadro/images. If you need more room, or would like to edit the logo further, you can always do so by opening the original fully layered PSD file located at Photoshop Files/quadro.psd</p></div>
<span class="boldtext">4. How do I setup the Featured Articles on the homepage? </span>
<div class="indent">
  <p>If you use this theme you will need to have a featured article on your hompage. These featured articles are pulled from a category within your blog. First, you need to make a category called "Featured Articles." You must spell it correctly in order for it to work. Once you have created to category, simply add posts to it when you want them to show up as your featured article. Only one featured article is displayed at a time. </p>
  <p>On a side note, you can add your article to other categoriest as well and still have it show up as a featured article by simply adding the article to the Featured Articles section in addition to its normal category. </p>
    </div>